---
name: Continuous Delivery
on:
  push:
    branches:
    - main
    paths:
    - vnet.yml

jobs:
  apply:
    name: Apply with Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}  
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: tf-init
        run: terraform init -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
